import { ArrayFn1 } from './array/ex1';
import { ArrayFn2 } from './array/ex2';
import { ArrayFn3 } from './array/ex3';
import { ArrayFn4 } from './array/ex4';
import { ArrayFn5 } from './array/ex5';
import { ArrayFn6 } from './array/ex6';
import { ArrayFn7 } from './array/ex7';
import { ArrayFn8 } from './array/ex8';
import { ArrayFn9 } from './array/ex9';
import { ArrayFn10 } from './array/ex10';
import { ArrayFn11 } from './array/ex11';
import { ArrayFn20 } from './array/ex20';
import { ArrayFn21 } from './array/ex21';
import { optionFn1 } from './option/ex1';
import { optionFn2 } from './option/ex2';
import { optionFn3 } from './option/ex3';
import { optionFn4 } from './option/ex4';
import { optionFn5 } from './option/ex5';
import { optionFn6 } from './option/ex6';
import { optionFn7 } from './option/ex7';
import { optionFn8 } from './option/ex8';
import { resultFn1 } from './result/ex1';
import { resultFn2 } from './result/ex2';
import { resultFn3 } from './result/ex3';
import { resultFn4 } from './result/ex4';
import { resultFn5 } from './result/ex5';
import { resultFn6 } from './result/ex6';
import { resultFn7 } from './result/ex7';
import { functionFn1 } from './function/ex1';
import { functionFn2 } from './function/ex2';
import { functionFn3 } from './function/ex3';

ArrayFn1();
ArrayFn2();
ArrayFn3();
ArrayFn4();
ArrayFn5();
ArrayFn6();
ArrayFn7();
ArrayFn8();
ArrayFn9();
ArrayFn10();
ArrayFn11();
ArrayFn20();
ArrayFn21();

optionFn1();
optionFn2();
optionFn3();
optionFn4();
optionFn5();
optionFn6();
optionFn7();
optionFn8();

resultFn1();
resultFn2();
resultFn3();
resultFn4();
resultFn5();
resultFn6();
resultFn7();

functionFn1();
functionFn2();
functionFn3();
